# Generated by Django 5.0.4 on 2024-04-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0003_alter_httpclient_port_alter_mqttbroker_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="httpclient",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Is Active"),
        ),
        migrations.AddField(
            model_name="mqttbroker",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Is Active"),
        ),
    ]
