name: Django Test

on: [push]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}

env:
    SECRET_KEY: ${{ secrets.SECRET_KEY }}
    
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"
            
            - name: Display Python version
              run: python -c "import sys; print(sys.version)"
            
            - name: Install dependencies
              run: make install

            - name: Run Test with pytest
              run: make test
